services:
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
      target: ${NODE_ENV:-dev}
    container_name: rental-backend
    restart: unless-stopped
    env_file:
      - ./server/.env # backend env file
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/app/src
      - ./server/prisma:/app/prisma
      - ./server/package.json:/app/package.json
      - ./server/package-lock.json:/app/package-lock.json
      - /app/node_modules
    networks:
      - rental-network
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             npm run dev"

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
      target: ${NODE_ENV:-dev}
    container_name: rental-frontend
    restart: unless-stopped
    env_file:
      - ./client/.env # frontend env file
    ports:
      - "5173:5173"
      - "80:80"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/package.json:/app/package.json
      - ./client/package-lock.json:/app/package-lock.json
      - ./client/vite.config.js:/app/vite.config.js
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - rental-network

networks:
  rental-network:
    driver: bridge
